server:
  port: 7171
spring:
  profiles:
    active: native
  application:
    name: SPRING-GATEWAY
  devtools:
    livereload:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: USER
          uri: lb://USER
          predicates:
            - Path=/api/v1/**
        - id: AUTH
          uri: lb://AUTH
          predicates:
            - Path=/api/**
        - id: TRANSACTION
          uri: lb://TRANSACTION
          predicates:
            - Path=/api/v1/**
